apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clair-hacbs-vj4v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clair-hacbs-vj4v
    app.kubernetes.io/part-of: hacbs
  name: clair-hacbs-vj4v
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: clair-hacbs-vj4v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: clair-hacbs-vj4v
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jsztuka-tenant/hacbs/clair-hacbs-vj4v@sha256:cd7cb101ada458544229b707b136c0deec651320d62d5f0831599bffeb22774c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
