apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clair-hacbs-vj4v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clair-hacbs-vj4v
    app.kubernetes.io/part-of: hacbs
  name: clair-hacbs-vj4v
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: clair-hacbs-vj4v
status:
  loadBalancer: {}
