apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clair-hacbs-vj4v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jsztuka-tenant/hacbs/clair-hacbs-vj4v@sha256:cd7cb101ada458544229b707b136c0deec651320d62d5f0831599bffeb22774c
        name: container-image
        resources: {}
status: {}
