apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clair-hacbs-vj4v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clair-hacbs-vj4v
    app.kubernetes.io/part-of: hacbs
  name: clair-hacbs-vj4v8mv3
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: clair-hacbs-vj4v
    weight: 100
status: {}
